### ISSUE TITLE
Help maintaining/expanding hyuga?

### ISSUE THREAD

**Issue by CFiggers** [sakuraiyuta/hyuga#19]
Hi there.

I have a local clone of hyuga working with Hy 1.0.0 and Hyrule 0.7, which seem to me like reasonably stable targets for tooling support to aim for.

Are you still active and interested at all in having collaborators on this project? I have some experience implementing LSP spec features for another language and would be interested in adding to hyuga, if there's someone who can review and merge PRs. 

I maintain [hylang/vscode-hy](https://GitHub.com/hylang/vscode-hy) and would like to integrate a language server for completion, go-to definition, hover documentation, document formatting, and eventually inline diagnostics. I'd be happy to vendor hyuga for that.

Thanks!

**Comment by sakuraiyuta** [comment]
@CFiggers 
Thank you for supporting Hy 1.0.0.

I had just heard about the release of Hy 1.0.0 and was hoping to support it.
I won't abandon this project, but it's difficult to continue development stably, so I needed help.
If you become a contributor, I would be very happy.

I am aware of the existence of hylang/vscode-hy, and if hyuga is eventually integrated into that, that would be very desirable.

Would you please send a PR?
I would like to merge it here and check it out.

**Comment by CFiggers** [comment]
@sakuraiyuta 
Happy to help out. I just sent in a PR that updates for Hy 1.0.0 and Hyrule 0.0.7, plus fixes some bugs.

I also got the tests passing. It seems like those may have been broken for a while now. A number of the function signatures were out of sync with the rest of the project. But they're all passing now (in my environment at least).

**Comment by sakuraiyuta** [comment]
@CFiggers 

I would like to sincerely thank you for your great work.

Hyuga prioritizes ‘just making things work,’ and I’m fully aware that the code is quite messy.
I can easily imagine that it must have required a great deal of patience to make these fixes.

I believe I will be able to check your PR in my environment and post a review if necessary by the end of this weekend.

**Comment by sakuraiyuta** [comment]
@CFiggers 

Thank you for your great works.
#20 is already merged and now we can say "hy 1.0.0 ready"!

Hyuga is still experimental, but I intend to continue its development so that Hy language users can enjoy a better development experience.
I’m glad you’ve taken an interest in this project. Please feel free to get involved, including any suggestions for new features.
